





export const metadata = {
  title: "Mridul Singh Saklani - Web Developer",
  description: "Generated by create next app",
};


export default function AdminLayout({ children }) {
  return (
    <html lang="en">
      
    
      <body
        className={` antialiased text-slate-500 bg-slate-900`}
       
      >
        
     

       
        {children}
       
        
        
     

      </body>
     
    </html>
  );
}
