
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ReduxProvider from "@/Store/ReduxProvider";
import SessionWrapper from "@/components/SessionWrapper";
import { Nunito } from 'next/font/google';
import AnimatedCursor from "react-animated-cursor"



export const metadata = {
  title: "Mridul Singh Saklani - Web Developer",
  description: "Generated by create next app",
};
const  nunito = Nunito({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'], 
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
     <SessionWrapper>
      <body
        className={`${nunito.className} antialiased text-slate-500 bg-slate-900`}
        style={{ fontFamily: 'Nunito' }}
      >
        <ReduxProvider>
     

        <Navbar/>
        <AnimatedCursor
          innerSize={8}
          outerSize={20}
          color="37, 99, 235" 
          outerAlpha={0.4}
          innerScale={1.2}
          outerScale={2}
        />
        {children}
        <Footer/>
        
        
        </ReduxProvider>

      </body>
      </SessionWrapper>
    </html>
  );
}
